/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/yW30R1nCz0L
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { JSX, SVGProps } from "react"

export function Footer() {
  return (
    <footer className="p-6 md:py-12 w-full bg-background border-t-2 border-t-gray-950 dark:border-t-slate-200 fixed bottom-0 left-0">
      <div className="container max-w-7xl flex flex-col sm:flex-row items-center justify-between gap-6">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          
          <span className="text-lg font-semibold"> RoNotBroYT</span>
        </Link>
        {/* <nav className="flex gap-4 sm:gap-6">
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Home
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            About
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Products
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Contact
          </Link>
        </nav> */}
        <p className="text-sm text-gray-500 dark:text-gray-400">Made by Benjy Ross, <Link href="https://github.com/brrock">My github, </Link> <Link href="https://benjyross.xyz">My website</Link> </p>
      </div>
    </footer>
  )
}


